---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tailscale-operator
  namespace: kube-system
spec:
  repo: https://great-tuna.github.io/helm-charts
  chart: tailscale-operator
  createNamespace: true
  targetNamespace: tailscale-operator
  valuesContent: |-
    azureKeyVaultSecret:
      vaultName: lon-k3s-great-tuna
    tailscale-operator:
      operatorConfig:
        defaultTags:
          - "tag:lon-k3s-operator"
        hostname: lon-k3s
      proxyConfig:
        defaultTags: "tag:lon-k3s-service"
  version: 0.1.1
